In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Importing data
from pathlib import Path
base_dir = Path.cwd()
fpath= os.path.join(base_dir, "DATA", "GTPvar.csv")
data=pd.read_csv(fpath,index_col=0)

In [3]:

# Check the missing values columnwise
data.isnull().sum(axis=1)

# Creates a new variable NApresent which will 
# contain the number of NAs in each row
data['NApresent']=data.isnull().sum(axis=1)

# No.of variables under each category
data['NApresent'].value_counts()

# Extract those rows with no NAs and find if the variables 
# have any relationship 
df=data[data['NApresent']==0]   


#drop the NApresent variable
df=df.drop(columns=['NApresent'])  

# convert to numpy array
df_mat = df.to_numpy()

#rank of the matrix
np.linalg.matrix_rank(df_mat)

#svd decomposition
VT, s, U = np.linalg.svd(df_mat.T)

#tolerence level
tol = 1e-8
# remove columns that are below tolerance level
rank = min(df_mat.shape) - np.abs(s)[::-1].searchsorted(tol)    
print("Rank of the matrix with no missing values is:", rank)

#choose the null space relationship
null_space = VT[:, rank:]
null_space = null_space.T
print("The null space relationships are:")
print(null_space)

Rank of the matrix with no missing values is: 2
The null space relationships are:
[[ 0.04739533 -0.5187747   0.51908568 -0.66965896  0.10360222]
 [ 0.25290917 -0.74555246 -0.49550562  0.25256403  0.26622185]
 [-0.69130722  0.0661908  -0.47253232 -0.41182833  0.35330403]]
